### ISSUE TITLE
The Interpreter

### ISSUE THREAD

**Issue by gnurenga** [aryakk04/python-training#1]
## Get Started

* Learn how to use interpreter
* try all arithmetic operation in interpreter
* learn how to use print statement on Interpreter.

## Reference
1. http://openbookproject.net/thinkcs/python/english2e/ch01.html

**Comment by gnurenga** [comment]
* Create a folder helloworld
* Create a file interpreter.md
* Put all your try out in that file.

The markdown output should be like

`>> test`

**Comment by gnurenga** [comment]
Create a branch and send a merge request @aryakk04. Any doubt you can ask in the comments section

**Comment by gnurenga** [comment]
#3 Thanks for the changes. Do you have any doubts ?

**Comment by aryakk04** [comment]
Interpreter section is clear for me.

**Comment by gnurenga** [comment]
:+1:  Ok then I will close this issue.
